name: a1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - lightgbm
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - Flask
  - pytest
  - scipy
  - joblib
  - plotly
  - streamlit
  - shap
  - pytest-cov
  - black
  - flake8
  - isort
  - pre-commit
  - git
  - pip
  - pip:
    - optuna
    - mlflow
    - dash
    - pyyaml
    - python-dotenv