name: a1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch
  - flask
  - scipy
  - joblib
  - ipython
  - jupyter
  - xgboost
  - pip
  - pip:
    - optuna
    - shap
    - plotly
    - dash
    - pyyaml
    - python-dotenv